spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: guest
    password: guest
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5430/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
server:
  port: 8080
  servlet:
    context-path: /monolith

rabbitmq:
  exchange: payment-exchange
  successRoutingKey: payment.success
  failureRoutingKey: payment.failure
  successQueue: payment-success-queue
  failureQueue: payment-failure-queue

payment:
  url: http://api-gateway:8082/payment/api