spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5429/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: monolith
          uri: ${MONOLITH:http://localhost:8080}
          predicates:
            - Path=/monolith/api/**
        - id: hotels
          uri: ${HOTELS:http://localhost:8085}
          predicates:
            - Path=/hotels/api/**
        - id: payment
          uri: ${HOTELS:http://localhost:8081}
          predicates:
            - Path=/payment/api/**
server:
  port: ${API_GATEWAY_PORT:8082}

server-user:
  credential: ${SERVER_USER_PASS:pass}
  name: ${SERVER_USER_NAME:name}